import { Container, Paper, Flex } from "@mantine/core";
import Head from "next/head";
import ToggleThemesButton from "@/components/ToggleThemesButton";
import ObjectMenu from "@/components/navigation/ObjectMenu";

const MasterLayout = ({ children }) => {
  return (
    <Container fluid>
      <Head>
        <title>Next.js with Mantine and TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper my={16}>
        <ToggleThemesButton />
      </Paper>
      <Flex>
        <ObjectMenu />
        {children}
      </Flex>
    </Container>
  );
};

export default MasterLayout;
